variables:
  DOCKER_REGISTRY: 450746307223.dkr.ecr.us-west-2.amazonaws.com
  AWS_DEFAULT_REGION: us-west-2
  #DOCKER_HOST: tcp://docker:2375
  APP_NAME: dev-trukkermaqsam
  REPOSITORY_NAME: product20
  TAG_LATEST: $CI_REGISTRY_IMAGE/hello-world
  #DOCKER_DRIVER: over lay2
  #DOCKER_TLS_CERTDIR: ""

publish:
  stage: build
  image: 
    name: docker:20.10
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip git
    #- pip install awscli
    - pip3 install --no-cache-dir awscli
    - aws --version
    #- amazon-linux-extras install docker credentials
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY

    - aws --version
    - hostname
    - docker info
  script:
    - docker build -t $DOCKER_REGISTRY/$REPOSITORY_NAME:latest .
    - docker tag $DOCKER_REGISTRY/$REPOSITORY_NAME:latest $DOCKER_REGISTRY/$REPOSITORY_NAME:latest
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$REPOSITORY_NAME:latest
